from typing import List, Dict, Any, Callable, Optional
from dataclasses import dataclass
from tools import execute_agent_tools, TOOLS


@dataclass
class Agent:
    """
    Similar to OpenAI Swarm's Agent class.
    """
    name: str
    instructions: str  # System prompt
    functions: List[str] = None  # List of tool names this agent can use
    
    def __post_init__(self):
        if self.functions is None:
            self.functions = []
    
    def get_available_functions(self) -> str:
        """Get description of functions this agent can use"""
        if not self.functions:
            return "No tools available."
        
        output = "AVAILABLE FUNCTIONS:\n"
        for func_name in self.functions:
            if func_name in TOOLS:
                tool = TOOLS[func_name]
                output += f"  • {func_name}: {tool['description']}\n"
                output += f"    Example: {tool['example']}\n"
        return output
    
    def get_full_instructions(self) -> str:
        """Get complete instructions including available functions"""
        instructions = self.instructions + "\n\n"
        instructions += self.get_available_functions()
        instructions += """
To use a function, write: TOOL_CALL: function_name(arguments)
To transfer to another agent, write: HANDOFF: agent_name
"""
        return instructions


@dataclass
class Response:
    """
    Response from agent execution.
    Similar to Swarm's Response object.
    """
    messages: List[str]
    agent: Agent
    context_variables: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.context_variables is None:
            self.context_variables = {}


class Swarm:
    """
    Swarm orchestrator.
    Manages agent execution and handoffs.
    """
    
    def __init__(self):
        self.agents: Dict[str, Agent] = {}
        self.current_agent: Optional[Agent] = None
        self.context_variables: Dict[str, Any] = {}
    
    def register_agent(self, agent: Agent):
        """Register an agent"""
        self.agents[agent.name] = agent
    
    def run(self, agent: Agent, query: str, llama_client) -> Response:
        """
        Run an agent with a query.
        
        Args:
            agent: Starting agent
            query: User's question
            llama_client: Function to call Llama (your query_llama)
        
        Returns:
            Response object with results
        """
        self.current_agent = agent
        messages = []
        
        # Get agent's full instructions
        full_instructions = agent.get_full_instructions()
        
        # Query the agent
        agent_response = llama_client(full_instructions, query, temperature=0.3)
        
        # Execute any tool calls
        agent_response = execute_agent_tools(agent_response)
        
        messages.append(agent_response)
        
        # Check for handoff
        handoff_agent = self._check_handoff(agent_response)
        
        if handoff_agent:
            print(f"\n Handing off from {agent.name} to {handoff_agent.name}...\n")
            # Recursive call with new agent
            handoff_response = self.run(handoff_agent, agent_response, llama_client)
            messages.extend(handoff_response.messages)
            agent = handoff_response.agent
        
        return Response(
            messages=messages,
            agent=agent,
            context_variables=self.context_variables
        )
    
    def _check_handoff(self, agent_response: str) -> Optional[Agent]:
        """Check if agent wants to handoff to another agent"""
        import re
        
        # Look for HANDOFF: agent_name
        pattern = r'HANDOFF:\s*(\w+)'
        match = re.search(pattern, agent_response, re.IGNORECASE)
        
        if match:
            agent_name = match.group(1)
            return self.agents.get(agent_name)
        
        return None


# test code generated by claude

if __name__ == "__main__":
    print("Testing Swarm-style Agents\n")
    print("=" * 60)
    
    # Create agents
    scholar = Agent(
        name="Scholar",
        instructions="""You are Scholar, a research assistant.
Answer questions accurately and use tools when needed.""",
        functions=["add", "multiply"]
    )
    
    fact_checker = Agent(
        name="FactChecker",
        instructions="""You are FactChecker, a validator.
Review answers for accuracy.""",
        functions=[]
    )
    
    # Create swarm
    swarm = Swarm()
    swarm.register_agent(scholar)
    swarm.register_agent(fact_checker)
    
    # Test
    print("Scholar's full instructions:")
    print(scholar.get_full_instructions())